server:
  port: 8000


spring:
  application:
    name: cloudcon-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/szh123456789/Cloudconfig
          search-paths: cloudDemo/gitconfig
          default-label: master
